:toc: left
:toctitle: 目次
:sectnums:
:sectanchors:
:sectinks:
:chapter-label:

= fuyu-note - DDD

== *オブジェクト指向*

クラス＝モジュール＝型＝概念
クラスが属性（インスタンス変数）と操作（メソッド）をカプセル化して定義する単位であり、かつモデル化対象に存在する概念を表現する際の単位であり、プログラミングの際に自由に導入できるユーザー定義可能なデータ型「抽象データ型（abstract data type）」であり、それがオブジェクト指向でソフトウェアを作っていく際の基本的な管理対象としてのモジュールの単位になる、

「関係するデータと手続きのカプセル化」
「クラスによるオブジェクトの抽象化」
「汎化（継承）によるクラス分類」
「関連によるオブジェクトの参照」
「集約による全体部分管理（コンポジット）」
「ポリモルフィズム（多義性/多相性/多態性）によるインタフェース実現」
「自律した状態マシンとしてのオブジェクト」
「開放閉鎖モジュールとしてのオブジェクト」


カプセル化:: モジュールを公開部分と非公開部分に分け、公開部分のみ参照するように作成しておく。

継承:: 共通の性質に着目して一般的なクラスを定義したり、渡久地の性質に着目して特殊化されたクラスを定義したりすることで、クラスの階層構造を作ることができる。「is-a」の関係。

ポリモーフィズム:: メッセージを送信する側のオブジェクトは、同一のメッセージを異るオブジェクトに送信するが、メッセージを受信する側のオブジェクトは、それぞれ異る振る舞いを行う。

開放閉鎖モジュールとしてのオブジェクト:: 外部にはインタフェースとして抽象クラスだけを公開し，データ構造や機能は抽象クラスのインタフェースを守るためそのサブクラスとして実装

== *UMLの整理*

概念モデル:: モデル化対象である業務領域に登場する、その業務のしくみを表現するのに必要不可欠なキーとなる構成要素を概念クラスとして定義し、そうした概念クラスどうしの関係として業務を再構成したもの

クラス図:: システム内のオブジェクトタイプとそれらの間に存在する各種の静的な関係を記述。クラスのプロパティと操作、オブジェクト同士がどのように結合されるかにかかわる制約も表す。
 


== *DDDの概念整理*

ドメイン:: チームが取り組んでいる事業全体

コアドメイン:: 組織を成功に導くためにもっとも重要なもの。事業的にほかと差別化されており、最優先で取り組まれる。置かれている状況によって、コアドメインが変化していくことがある。

サブドメイン:: コアドメインから使われる必要な部分
 * 支援サブドメイン: 業務的に特別だが、コアドメインほど重要ではないもの +
 * 汎用サブドメイン: 業務的に特別ではないが、全体として必要なもの（認証系、外部ERPなど差し替え可能なもの）

境界づけられたコンテキスト:: 戦略的/業務的なドメインの問題を技術的なソリューションにて解決するもの。ユビキタス言語の意味が変わる境界で「境界づけられたコンテキスト」を分割して管理する。


TIP: 1つの「コアドメイン（もしくはサブドメイン）」に、1つの「境界づけられたコンテキスト」が対応している状態が最適


コンテキストマップ::  複数の「境界づけられたコンテキスト」間の関係を俯瞰する地図となり、システムの全体像や相互関係を把握することができる。
「境界づけられたコンテキスト」を丸で囲み、コンテキスト間の関係を線でつなぐシンプルな図。チーム間のコミュケーション関係を示す図の意味合いが強い。コンテキストマップは、連携するチームとの関係性を示すドキュメントであるため、なるべく早いうちに作成することが良い。
 * 組織パターン
 ** パートナーシップ +
 2つのチームにおいて協力的な関係が成り立つ
 ** 別別の道 +
 コンテキスト間で統合を行わない
 ** 順応者 +
 2つのチーム間において、上流側が下流側の要望を考慮する必要がない状態
 ** 顧客／供給者 +
 上流側チームの成否が下流側チームの成否に影響を大きく与える場合、上流側のチームが下流側のチームに対して適切なサポートを行う。
 * 統合パターン
 ** 共有カーネル +
 「共有カーネル」は複数ドメインにおいて共有が必要な部分に、共通で使用するドメインモデルを構築してソースコードレベルで共有する。
 ** 巨大な泥団子 +
 既存システムが大規模で複雑な場合、そのまま大きな固まりとして捉える。
 ** 公開ホストサービス +
 「境界づけられたコンテキスト」の内容にアクセスできる公開サービス。
 ** 公表された言語 +
 2つの境界づけられたコンテキスト内のモデルを変換する場合の共通の言語。
 ** 腐敗防止層 +
 下流側のチームが上流側の機能を自コンテキストのドメインモデルとして変換するため。

TIP: 他のコンテキストにアクセスできない場合でも、自分のコンテキストが正しく動作するように設計

結果整合性:: リアルタイム同期が行われなくても、状態の整合性が最終的に取れていれば問題無いこと

ミニマル指向:: コンテキスト間で同期するデータを最小にし、リモートモデルの属性のうち必要なものだけをローカルモデルに連携させること

エンティティ:: 一意なものを表現する概念。長期にわたって変更（ライフサイクル）を管理する必要があるもの。

値オブジェクト:: 一意に識別して変更を管理する必要がないもの

== *ヘキサゴナルアーキテクチャ概念整理*

ヘキサゴナルアーキテクチャ:: UI層やインフラストラクチャ層の部分をフロントエンドやバックエンドといった１つの塊ではなく、独立したアダプタによって適切に管理する。
アプリケーション（ドメイン）層を中心に捉え、ユーザー操作／自動テストといった入力側もデータベース／モックといった出力側も、全てまとめて差し替え可能な外部インターフェイスとして扱う
